/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiPublicArticlesRouteImport } from './routes/api/public/articles'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google/callback'
import { Route as ApiPublicHooksDailyAutopilotRouteImport } from './routes/api/public/hooks/daily-autopilot'
import { Route as ApiPublicHooksRefillCalendarRouteImport } from './routes/api/public/hooks/refill-calendar'
import { Route as ApiPublicHooksStripeRouteImport } from './routes/api/public/hooks/stripe'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img/$'
import { Route as ApiPublicShopifyBillingRouteImport } from './routes/api/public/shopify/billing'
import { Route as ApiPublicShopifyCallbackRouteImport } from './routes/api/public/shopify/callback'
import { Route as ApiPublicShopifyInstallRouteImport } from './routes/api/public/shopify/install'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiPublicArticlesRoute = ApiPublicArticlesRouteImport.update({
  id: '/api/public/articles',
  path: '/api/public/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyAutopilotRoute =
  ApiPublicHooksDailyAutopilotRouteImport.update({
    id: '/api/public/hooks/daily-autopilot',
    path: '/api/public/hooks/daily-autopilot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefillCalendarRoute =
  ApiPublicHooksRefillCalendarRouteImport.update({
    id: '/api/public/hooks/refill-calendar',
    path: '/api/public/hooks/refill-calendar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStripeRoute = ApiPublicHooksStripeRouteImport.update({
  id: '/api/public/hooks/stripe',
  path: '/api/public/hooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyBillingRoute = ApiPublicShopifyBillingRouteImport.update({
  id: '/api/public/shopify/billing',
  path: '/api/public/shopify/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyCallbackRoute =
  ApiPublicShopifyCallbackRouteImport.update({
    id: '/api/public/shopify/callback',
    path: '/api/public/shopify/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopifyInstallRoute = ApiPublicShopifyInstallRouteImport.update({
  id: '/api/public/shopify/install',
  path: '/api/public/shopify/install',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/articles': typeof ApiPublicArticlesRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/hooks/daily-autopilot': typeof ApiPublicHooksDailyAutopilotRoute
  '/api/public/hooks/refill-calendar': typeof ApiPublicHooksRefillCalendarRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/shopify/billing': typeof ApiPublicShopifyBillingRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify/install': typeof ApiPublicShopifyInstallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/api/public/articles': typeof ApiPublicArticlesRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/hooks/daily-autopilot': typeof ApiPublicHooksDailyAutopilotRoute
  '/api/public/hooks/refill-calendar': typeof ApiPublicHooksRefillCalendarRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/shopify/billing': typeof ApiPublicShopifyBillingRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify/install': typeof ApiPublicShopifyInstallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/articles': typeof ApiPublicArticlesRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/hooks/daily-autopilot': typeof ApiPublicHooksDailyAutopilotRoute
  '/api/public/hooks/refill-calendar': typeof ApiPublicHooksRefillCalendarRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/shopify/billing': typeof ApiPublicShopifyBillingRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify/install': typeof ApiPublicShopifyInstallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/blog'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/auth/callback'
    | '/blog/$slug'
    | '/blog/'
    | '/api/public/articles'
    | '/api/public/google/callback'
    | '/api/public/hooks/daily-autopilot'
    | '/api/public/hooks/refill-calendar'
    | '/api/public/hooks/stripe'
    | '/api/public/img/$'
    | '/api/public/shopify/billing'
    | '/api/public/shopify/callback'
    | '/api/public/shopify/install'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/auth/callback'
    | '/blog/$slug'
    | '/blog'
    | '/api/public/articles'
    | '/api/public/google/callback'
    | '/api/public/hooks/daily-autopilot'
    | '/api/public/hooks/refill-calendar'
    | '/api/public/hooks/stripe'
    | '/api/public/img/$'
    | '/api/public/shopify/billing'
    | '/api/public/shopify/callback'
    | '/api/public/shopify/install'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/blog'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/auth_/callback'
    | '/blog/$slug'
    | '/blog/'
    | '/api/public/articles'
    | '/api/public/google/callback'
    | '/api/public/hooks/daily-autopilot'
    | '/api/public/hooks/refill-calendar'
    | '/api/public/hooks/stripe'
    | '/api/public/img/$'
    | '/api/public/shopify/billing'
    | '/api/public/shopify/callback'
    | '/api/public/shopify/install'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicArticlesRoute: typeof ApiPublicArticlesRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
  ApiPublicHooksDailyAutopilotRoute: typeof ApiPublicHooksDailyAutopilotRoute
  ApiPublicHooksRefillCalendarRoute: typeof ApiPublicHooksRefillCalendarRoute
  ApiPublicHooksStripeRoute: typeof ApiPublicHooksStripeRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
  ApiPublicShopifyBillingRoute: typeof ApiPublicShopifyBillingRoute
  ApiPublicShopifyCallbackRoute: typeof ApiPublicShopifyCallbackRoute
  ApiPublicShopifyInstallRoute: typeof ApiPublicShopifyInstallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/public/articles': {
      id: '/api/public/articles'
      path: '/api/public/articles'
      fullPath: '/api/public/articles'
      preLoaderRoute: typeof ApiPublicArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-autopilot': {
      id: '/api/public/hooks/daily-autopilot'
      path: '/api/public/hooks/daily-autopilot'
      fullPath: '/api/public/hooks/daily-autopilot'
      preLoaderRoute: typeof ApiPublicHooksDailyAutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refill-calendar': {
      id: '/api/public/hooks/refill-calendar'
      path: '/api/public/hooks/refill-calendar'
      fullPath: '/api/public/hooks/refill-calendar'
      preLoaderRoute: typeof ApiPublicHooksRefillCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/stripe': {
      id: '/api/public/hooks/stripe'
      path: '/api/public/hooks/stripe'
      fullPath: '/api/public/hooks/stripe'
      preLoaderRoute: typeof ApiPublicHooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/billing': {
      id: '/api/public/shopify/billing'
      path: '/api/public/shopify/billing'
      fullPath: '/api/public/shopify/billing'
      preLoaderRoute: typeof ApiPublicShopifyBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/callback': {
      id: '/api/public/shopify/callback'
      path: '/api/public/shopify/callback'
      fullPath: '/api/public/shopify/callback'
      preLoaderRoute: typeof ApiPublicShopifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/install': {
      id: '/api/public/shopify/install'
      path: '/api/public/shopify/install'
      fullPath: '/api/public/shopify/install'
      preLoaderRoute: typeof ApiPublicShopifyInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicArticlesRoute: ApiPublicArticlesRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
  ApiPublicHooksDailyAutopilotRoute: ApiPublicHooksDailyAutopilotRoute,
  ApiPublicHooksRefillCalendarRoute: ApiPublicHooksRefillCalendarRoute,
  ApiPublicHooksStripeRoute: ApiPublicHooksStripeRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
  ApiPublicShopifyBillingRoute: ApiPublicShopifyBillingRoute,
  ApiPublicShopifyCallbackRoute: ApiPublicShopifyCallbackRoute,
  ApiPublicShopifyInstallRoute: ApiPublicShopifyInstallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
